### ISSUE TITLE
Vulnerability: Rest api can be accessed by unauthenticated users

### ISSUE THREAD

**Issue by adelinn** [bcc-code/bcc-wp#21]
BCC-login plugin won't prevent unauthenticated users from accessing the rest api (wp-json).
However the amount of data that can be stolen is very limited.

Severity: Medium
CVSS score: [5.3 (Medium)](https://www.first.org/cvss/calculator/3.1#CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N)

**Comment by cs1m0n** [comment]
Hello, I have now tested several use-cases and everything worked as expected.

Only when the **Default Control Access** setting is set to **Public**, the **wp-json/wp/v2/posts**, for example, will return posts which have the _Post Audience_ set to **Public** or **Default** (not set at all).

To give you a bit of context, the (new) BCC Login plugin implements a level of control access, so that the websites using the plugin can remain public (but have some pages/posts/blocks) available only for authenticated users, can also be accessible with a login (how it is the case with the local church websites right now), but also only Organization specific, so that only members belonging to that organization can access the website.

Public posts (on a public site) are anyway available on the website itself so this should not be considered a vulnerability.

I will close this for now.
Thank you!

@rvanoord
